# Repos
tap "jandedobbeleer/oh-my-posh"
tap "powershell/tap"

brew "zsh"
brew "oh-my-posh"
brew "powershell"
brew "zoxide"

cask "keepingyouawake"
cask "the-unarchiver"
cask "appcleaner"
brew "svgo"
brew "lazygit"
brew "ripgrep"
brew "fd"
brew "neovim"
brew "fnm"

cask "visual-studio-code"
